<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Multi-Marketplace Platform Registry & Field Schema
    |--------------------------------------------------------------------------
    |
    | Defines supported e-commerce marketplace platforms, their metadata,
    | branding, required official API fields, validation rules, and sandbox defaults.
    | Adding a new platform only requires declaring its schema here.
    |
    */

    'platforms' => [
        'TOKOPEDIA' => [
            'name' => 'Tokopedia',
            'code' => 'TOKOPEDIA',
            'color' => '#03AC0E',
            'bg_light' => 'rgba(3, 172, 14, 0.08)',
            'icon' => 'shopping-bag',
            'badge' => 'Tokopedia Seller API',
            'description' => 'Integrasi resmi via Tokopedia Developer & Fulfillment Service (FS) Open API.',
            'docs_url' => 'https://developer.tokopedia.com/openapi/guide/',
            'fields' => [
                [
                    'name' => 'store_name',
                    'label' => 'Nama Toko (Display Name)',
                    'type' => 'text',
                    'placeholder' => 'Contoh: Toko Berkah Fashion Official',
                    'required' => true,
                    'help' => 'Nama identifikasi toko Anda di dashboard Eskul AI.',
                    'validation' => 'required|string|max:150',
                ],
                [
                    'name' => 'shop_id',
                    'label' => 'Shop ID Tokopedia',
                    'type' => 'number',
                    'placeholder' => 'Contoh: 18293041',
                    'required' => true,
                    'help' => 'ID numerik toko Tokopedia Anda dari Seller Center.',
                    'validation' => 'required|numeric|digits_between:4,15',
                ],
                [
                    'name' => 'fs_id',
                    'label' => 'Fulfillment Service (FS) ID / Partner ID',
                    'type' => 'number',
                    'placeholder' => 'Contoh: 12948',
                    'required' => true,
                    'help' => 'ID aplikasi Partner/Developer yang terdaftar di Tokopedia Developer Console.',
                    'validation' => 'required|numeric',
                ],
                [
                    'name' => 'client_id',
                    'label' => 'Client ID (OAuth 2.0)',
                    'type' => 'text',
                    'placeholder' => 'Contoh: 4a6b2c8d1e0f...',
                    'required' => true,
                    'help' => 'Client ID aplikasi dari Tokopedia Developer Console.',
                    'validation' => 'required|string|min:6|max:100',
                ],
                [
                    'name' => 'client_secret',
                    'label' => 'Client Secret',
                    'type' => 'password',
                    'placeholder' => '••••••••••••••••',
                    'required' => true,
                    'is_secret' => true,
                    'help' => 'Kunci rahasia API dari Tokopedia Developer Console.',
                    'validation' => 'required|string|min:6',
                ],
            ],
            'sandbox_defaults' => [
                'store_name' => 'Official Tokopedia Demo Store',
                'shop_id' => '19283746',
                'fs_id' => '15520',
                'client_id' => 'tkpd_client_test_7788',
                'client_secret' => 'tkpd_sec_sandbox_9922aa88bb',
            ],
        ],

        'SHOPEE' => [
            'name' => 'Shopee',
            'code' => 'SHOPEE',
            'color' => '#EE4D2D',
            'bg_light' => 'rgba(238, 77, 45, 0.08)',
            'icon' => 'shopping-cart',
            'badge' => 'Shopee Open Platform v2',
            'description' => 'Koneksi API resmi via Shopee Open Platform dengan HMAC-SHA256 signature.',
            'docs_url' => 'https://open.shopee.com/documents',
            'fields' => [
                [
                    'name' => 'store_name',
                    'label' => 'Nama Toko (Display Name)',
                    'type' => 'text',
                    'placeholder' => 'Contoh: Bintang Mode Official',
                    'required' => true,
                    'help' => 'Nama toko Shopee Anda.',
                    'validation' => 'required|string|max:150',
                ],
                [
                    'name' => 'shop_id',
                    'label' => 'Shop ID Shopee',
                    'type' => 'number',
                    'placeholder' => 'Contoh: 88123901',
                    'required' => true,
                    'help' => 'ID unik toko Shopee (dapat dilihat di Seller Centre atau respon otorisasi).',
                    'validation' => 'required|numeric|digits_between:4,15',
                ],
                [
                    'name' => 'partner_id',
                    'label' => 'Partner ID',
                    'type' => 'number',
                    'placeholder' => 'Contoh: 2004567',
                    'required' => true,
                    'help' => 'Partner ID developer dari Shopee Open Platform Console.',
                    'validation' => 'required|numeric',
                ],
                [
                    'name' => 'partner_key',
                    'label' => 'Partner Key / Secret',
                    'type' => 'password',
                    'placeholder' => '••••••••••••••••',
                    'required' => true,
                    'is_secret' => true,
                    'help' => 'Kunci enkripsi Partner Key untuk kalkulasi SHA256 sign.',
                    'validation' => 'required|string|min:6',
                ],
                [
                    'name' => 'access_token',
                    'label' => 'Access Token',
                    'type' => 'password',
                    'placeholder' => 'Contoh: shp_act_991823ab...',
                    'required' => true,
                    'is_secret' => true,
                    'help' => 'Token otentikasi toko setelah seller mengizinkan akses aplikasi.',
                    'validation' => 'required|string|min:6',
                ],
            ],
            'sandbox_defaults' => [
                'store_name' => 'Bintang Mode Official (Shopee)',
                'shop_id' => '8899120',
                'partner_id' => '2004567',
                'partner_key' => 'shp_key_demo_66778899',
                'access_token' => 'shp_live_act_8899aabbccddeeff',
            ],
        ],

        'LAZADA' => [
            'name' => 'Lazada',
            'code' => 'LAZADA',
            'color' => '#0055FF',
            'bg_light' => 'rgba(0, 85, 255, 0.08)',
            'icon' => 'package',
            'badge' => 'Lazada Open Platform',
            'description' => 'Integrasi seller via Lazada Open Platform (GSP / Regional Seller API).',
            'docs_url' => 'https://open.lazada.com/doc/doc.htm',
            'fields' => [
                [
                    'name' => 'store_name',
                    'label' => 'Nama Toko (Display Name)',
                    'type' => 'text',
                    'placeholder' => 'Contoh: Metro Elektronik Lazada Store',
                    'required' => true,
                    'help' => 'Nama tampilan toko Lazada Anda.',
                    'validation' => 'required|string|max:150',
                ],
                [
                    'name' => 'seller_id',
                    'label' => 'Seller ID / Short Code',
                    'type' => 'text',
                    'placeholder' => 'Contoh: ID10ABCD88',
                    'required' => true,
                    'help' => 'ID unik akun penjual di Lazada Seller Center.',
                    'validation' => 'required|string|max:50',
                ],
                [
                    'name' => 'app_key',
                    'label' => 'App Key',
                    'type' => 'text',
                    'placeholder' => 'Contoh: 108291',
                    'required' => true,
                    'help' => 'App Key aplikasi terdaftar di Lazada Open Platform.',
                    'validation' => 'required|string|min:4|max:50',
                ],
                [
                    'name' => 'app_secret',
                    'label' => 'App Secret',
                    'type' => 'password',
                    'placeholder' => '••••••••••••••••',
                    'required' => true,
                    'is_secret' => true,
                    'help' => 'Kunci rahasia aplikasi Lazada.',
                    'validation' => 'required|string|min:6',
                ],
                [
                    'name' => 'access_token',
                    'label' => 'Seller Access Token',
                    'type' => 'password',
                    'placeholder' => 'Contoh: 50000201a08b...',
                    'required' => true,
                    'is_secret' => true,
                    'help' => 'Otorisasi token penjual yang masih berlaku.',
                    'validation' => 'required|string|min:6',
                ],
            ],
            'sandbox_defaults' => [
                'store_name' => 'Metro Living Official (Lazada)',
                'seller_id' => 'ID_LZD_99182',
                'app_key' => '108291',
                'app_secret' => 'lzd_sec_test_55443322',
                'access_token' => '50000201a08b99cc77dd88ee11',
            ],
        ],

        'TIKTOK_SHOP' => [
            'name' => 'TikTok Shop',
            'code' => 'TIKTOK_SHOP',
            'color' => '#000000',
            'bg_light' => 'rgba(0, 0, 0, 0.08)',
            'icon' => 'video',
            'badge' => 'TikTok Shop Partner API',
            'description' => 'Sinkronisasi e-commerce content-driven via TikTok Shop Partner Center.',
            'docs_url' => 'https://partner.tiktokshop.com/doc/page/63feff241b12b2028c0b56db',
            'fields' => [
                [
                    'name' => 'store_name',
                    'label' => 'Nama Toko (Display Name)',
                    'type' => 'text',
                    'placeholder' => 'Contoh: Glow & Tech Viral (TikTok Shop)',
                    'required' => true,
                    'help' => 'Nama akun toko TikTok Shop Anda.',
                    'validation' => 'required|string|max:150',
                ],
                [
                    'name' => 'shop_cipher',
                    'label' => 'Shop Cipher / Shop ID',
                    'type' => 'text',
                    'placeholder' => 'Contoh: GCPO_X92K81M',
                    'required' => true,
                    'help' => 'Shop Cipher resmi toko yang didapatkan dari respon autorisasi TikTok Shop.',
                    'validation' => 'required|string|min:4|max:100',
                ],
                [
                    'name' => 'app_key',
                    'label' => 'Partner App Key',
                    'type' => 'text',
                    'placeholder' => 'Contoh: 6ab89c2...',
                    'required' => true,
                    'help' => 'App Key dari TikTok Shop Partner Center.',
                    'validation' => 'required|string|min:4|max:64',
                ],
                [
                    'name' => 'app_secret',
                    'label' => 'App Secret',
                    'type' => 'password',
                    'placeholder' => '••••••••••••••••',
                    'required' => true,
                    'is_secret' => true,
                    'help' => 'App Secret dari TikTok Shop Partner Center.',
                    'validation' => 'required|string|min:6',
                ],
                [
                    'name' => 'access_token',
                    'label' => 'Authorized Access Token',
                    'type' => 'password',
                    'placeholder' => 'Contoh: ttp_act_9921477...',
                    'required' => true,
                    'is_secret' => true,
                    'help' => 'Token otentikasi toko TikTok Shop.',
                    'validation' => 'required|string|min:6',
                ],
            ],
            'sandbox_defaults' => [
                'store_name' => 'Glow & Tech Viral (TikTok Shop)',
                'shop_cipher' => 'GCPO_X92K81M_DEMO',
                'app_key' => '6ab89c2demo',
                'app_secret' => 'tt_sec_demo_992244',
                'access_token' => 'ttp_act_demo_live_token_77',
            ],
        ],
    ],
];
